### ISSUE TITLE
security_register functions Address mode 3 byte, why the register address get's left shifted? 

### ISSUE THREAD

**Issue by KestrelLuca** [libdriver/w25qxx#19]
### Please ask your question

Hello, I'm using a W25q16 chip and the read test is failing on the security registers test.
In the security_register functions (w25qxx_program_security_register, w25qxx_read_security_register, w25qxx_erase_security_register, etc) when using the quad spi in dula line (handle->spi_qspi == W25QXX_INTERFACE_SPI && handle->dual_quad_spi_enable != 0) the register's addresses are left shifted by 8 bits. This causes the QUAD SPI (on my stm32l475) to set the TEF flag ( Transfer error flag.This bit is set in indirect mode when an invalid address is being accessed in indirect mode).
The failure occurs on registers 2  (W25QXX_SECURITY_REGISTER_2 = 0x2000) and 3 (W25QXX_SECURITY_REGISTER_3 = 0x3000) since the addresses (being shifted) are out of bounds (Valid Address Range: 0x000000 to 0x1FFFFF for a 16 Megabit flash memory).
Can you please provide some explanation ?
Best regards

**Comment by libdriver** [comment]
Can you give me your stm32l475_interface.c, test program and test output.

**Comment by KestrelLuca** [comment]
Hi, thanks for your reply.
The interface .c file I've used for testing comes from the example project in the repo (project\stm32f767\driver\src) along with the qspi files (.c and .h in the project\stm32f767\interface). 
[qspi.c.txt](https://github.com/user-attachments/files/16177427/qspi.c.txt)
[qspi.h.txt](https://github.com/user-attachments/files/16177428/qspi.h.txt)
[stm32f767_driver_w25qxx_interface.c.txt](https://github.com/user-attachments/files/16177429/stm32f767_driver_w25qxx_interface.c.txt)
In these files, I've just made use of my delay routines and I've linked the CubeMx qspi initialization  (clock @40MHz with both mode 0 and mode 3 working):

```
void MX_QUADSPI_Init(void)
{
  /* USER CODE BEGIN QUADSPI_Init 0 */

  /* USER CODE END QUADSPI_Init 0 */

  /* USER CODE BEGIN QUADSPI_Init 1 */

  /* USER CODE END QUADSPI_Init 1 */
  /* QUADSPI parameter configuration*/
  hqspi.Instance = QUADSPI;
  hqspi.Init.ClockPrescaler = 1;
  hqspi.Init.FifoThreshold = 1;
  hqspi.Init.SampleShifting = QSPI_SAMPLE_SHIFTING_HALFCYCLE;
  hqspi.Init.FlashSize = 20;
  hqspi.Init.ChipSelectHighTime = QSPI_CS_HIGH_TIME_1_CYCLE;
  hqspi.Init.ClockMode = QSPI_CLOCK_MODE_0;
  if (HAL_QSPI_Init(&hqspi) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN QUADSPI_Init 2 */

  /* USER CODE END QUADSPI_Init 2 */

}
```

In the test code, after the board initialization, I call the following :
 ```
  if (w25qxx_register_test(W25Q16, W25QXX_INTERFACE_SPI, W25QXX_BOOL_TRUE)) {
      printf("\n************** EXT FLASH REG TEST: FAIL \n\n");
  } else {
      printf("\n************** EXT FLASH REG TEST: PASS \n\n");
  }

  if(w25qxx_read_test(W25Q16,  W25QXX_INTERFACE_SPI, W25QXX_BOOL_TRUE)) {
      printf("\n************** EXT FLASH READ TEST: FAIL \n\n");
  } else {
      printf("\n************** EXT FLASH READ TEST: PASS \n\n");
  }
```
Here are the results with the original w25qxx_security_register_t (driver_w25qxx.h)
```
/**
 * @brief w25qxx security register enumeration definition
 */
typedef enum
{
    W25QXX_SECURITY_REGISTER_1 = 0x1000,        /**< security register 1 */
    W25QXX_SECURITY_REGISTER_2 = 0x2000,        /**< security register 2 */
    W25QXX_SECURITY_REGISTER_3 = 0x3000,        /**< security register 3 */
} w25qxx_security_register_t;
```
[TestFAIL.txt](https://github.com/user-attachments/files/16177854/TestFAIL.txt)
here are the results with the modified w25qxx_security_register_t (driver_w25qxx.h) to overcome what looks like an incorrect 8-bit register address left shift
```
/**
 * @brief w25qxx security register enumeration definition
 */
typedef enum
{
    W25QXX_SECURITY_REGISTER_1 = 0x10/*00*/,        /**< security register 1 */
    W25QXX_SECURITY_REGISTER_2 = 0x20/*00*/,        /**< security register 2 */
    W25QXX_SECURITY_REGISTER_3 = 0x30/*00*/,        /**< security register 3 */
} w25qxx_security_register_t;
```

[TestPASS.txt](https://github.com/user-attachments/files/16177878/TestPASS.txt)
Regardless of the memory size, the security register addresses are always the same (according to the parts datasheets) and I can't explain the reason for the security register address shift. Can you please explain the reason for this operation?
Hope this helps and thanks for looking into this.
Best regards
Luca

**Comment by libdriver** [comment]
Hello, Your analysis is correct, and this enumeration is indeed incorrect. We have updated the latest driver and thank you very much for raising the issue. You can pull this driver again.

**Comment by KestrelLuca** [comment]
Thanks for looking into this. 
I've seen you have changed the register addresses (the enumeration) but shouldn't the bug be in the left shift on the functions (unless I'm missing any other purpose for those functions)?
Regards

**Comment by libdriver** [comment]
![1](https://github.com/user-attachments/assets/605ac844-3ffd-4c05-83ca-6a85dc896065)
![2](https://github.com/user-attachments/assets/b33736f4-ccfb-4a09-b4ad-e509833c3469)
![3](https://github.com/user-attachments/assets/152b24e4-d266-46ea-bad2-de5980b04e3a)
![4](https://github.com/user-attachments/assets/5e5fce9a-2248-49e7-a98e-d164765b571b)
![5](https://github.com/user-attachments/assets/43d40a31-2e87-40ed-912f-eb606d770339)

Your previous analysis was correct. In order to be compatible with SPI and QSPI interfaces at the same time, the design was changed to a right shifted 8-bit address as the enumeration of register addresses. According to the datasheet and the chip verification, the current modification is correct.

**Comment by KestrelLuca** [comment]
Thanks for your work and for fixing this.
