### ISSUE TITLE
w25qxx_set_status_x() wrong check after write

### ISSUE THREAD

**Issue by KestrelLuca** [libdriver/w25qxx#24]
### Describe the bug

w25qxx_set_status2() and w25qxx_set_status3() functions perform the check (after the write) always on Status Register 1 (W25QXX_COMMAND_READ_STATUS_REG1)

**Comment by libdriver** [comment]
Thank you for using LibDriver W25QXX.
![微信图片_20240906155710](https://github.com/user-attachments/assets/34f0c029-bcb2-4270-8fa2-69447e7fe65e)
![微信图片_20240906155714](https://github.com/user-attachments/assets/06862b00-5c48-423b-9f33-f51feca1d274)
![微信图片_20240906155717](https://github.com/user-attachments/assets/2130fded-3eb2-4e00-bdb4-c7f5a908875a)
![微信图片_20240906155720](https://github.com/user-attachments/assets/a6528603-8640-4635-b273-6dab4349763f)
According to the description in the datasheet, status register 1, status register 2, and status register 1 are different types of registers. The above is their description, and the driver processing seems to be correct.

**Comment by KestrelLuca** [comment]
Hi, thanks for your reply.
`uint8_t w25qxx_set_status3(w25qxx_handle_t *handle, uint8_t status)
{
    uint8_t res;
    uint8_t buf[2];
    uint32_t timeout;
    uint8_t status_check;
    
    if (handle == NULL)                                                                                  /* check handle */
    {
        return 2;                                                                                        /* return error */
    }   
    if (handle->inited != 1)                                                                             /* check handle initialization */
    {
        return 3;                                                                                        /* return error */
    }

    if (handle->spi_qspi == W25QXX_INTERFACE_SPI)                                                        /* spi interface */
    {
        if (handle->dual_quad_spi_enable != 0)                                                           /* enable dual quad spi */
        {
            res = a_w25qxx_qspi_write_read(handle, W25QXX_COMMAND_VOLATILE_SR_WRITE_ENABLE, 1,
                                           0x00000000, 0x00, 0x00,
                                           0x00000000, 0x00, 0x00,
                                           0x00, NULL, 0x00,
                                           NULL, 0x00, 0x00);                                            /* qspi write read */
            if (res != 0)                                                                                /* check result */
            {
                handle->debug_print("w25qxx: write enable failed.\n");                                   /* write enable failed */
               
                return 1;                                                                                /* return error */
            }
            buf[0] = status;                                                                             /* set status */
            res = a_w25qxx_qspi_write_read(handle, W25QXX_COMMAND_WRITE_STATUS_REG3, 1,
                                           0x00000000, 0x00, 0x00,
                                           0x00000000, 0x00, 0x00,
                                           0x00, (uint8_t *)buf, 1,
                                           NULL, 0x00, 1);                                               /* qspi write read */
            if (res != 0)                                                                                /* check result */
            {
                handle->debug_print("w25qxx: set status3 failed.\n");                                    /* set status3 failed */
               
                return 1;                                                                                /* return error */
            }
            
            timeout = 1000;                                                                              /* max 1000 ms */
            while (timeout != 0)                                                                         /* check timeout */
            {
                res = a_w25qxx_qspi_write_read(handle, W25QXX_COMMAND_READ_STATUS_REG1, 1,
                                               0x00000000, 0x00, 0x00,
                                               0x00000000, 0x00, 0x00,
                                               0x00, NULL, 0x00,
                                              (uint8_t *)&status_check, 1, 1);                           /* qspi write read */
                if (res != 0)                                                                            /* check result */
                {
                    handle->debug_print("w25qxx: get status1 failed.\n");                                /* get status1 failed */
                   
                    return 1;                                                                            /* return error */
                }`
this is the w25qxx_set_status3, as you can see, after the write, a read of this register is performed to confirm the correct write. the command being used is wrong, W25QXX_COMMAND_READ_STATUS_REG1 it has been used rather than W25QXX_COMMAND_READ_STATUS_REG3. the mistake is also present in the register 2

**Comment by KestrelLuca** [comment]
I see, my apologies I thought a read-back for each status register was missing where this has to be implemented in the application instead.
Thanks

**Comment by libdriver** [comment]
I am very happy that your issue has been successfully resolved. This driver use busy bit to check the changing status and you can also read the status at the application layer to check the changing status.
